# Generated by Django 2.2.6 on 2020-01-29 11:45

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200122_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
