# Generated by Django 2.2.6 on 2020-02-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200129_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
